services:
  db:
    container_name: 'law_db'
    image: postgres:16
    env_file:
      - .env.prod
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  law_app:
    container_name: "law_app"
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - "10001:10001"
    restart: always
    volumes:
      - ./app/uploads:/law/uploads:ro