"""empty message

Revision ID: 07a5596ba730
Revises: 5b8cad7cb8b1
Create Date: 2025-10-13 12:45:33.735711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a5596ba730'
down_revision: Union[str, Sequence[str], None] = '5b8cad7cb8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_psychology_scoring_student_year_semester'), 'psychology_scorings', type_='unique')
    op.create_unique_constraint('uq_psychology_scoring_student_year_semester', 'psychology_scorings', ['psychology_achievement_id', 'student_id_number', 'education_year_code', 'semester_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_psychology_scoring_student_year_semester', 'psychology_scorings', type_='unique')
    op.create_unique_constraint(op.f('uq_psychology_scoring_student_year_semester'), 'psychology_scorings', ['student_id_number', 'education_year_code', 'semester_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
