"""empty message

Revision ID: 08cacb95bcc3
Revises: 0f199394c517
Create Date: 2025-10-14 23:39:55.705711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cacb95bcc3'
down_revision: Union[str, Sequence[str], None] = '0f199394c517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_education_history', sa.Column('order', sa.Integer(), nullable=False))
    op.add_column('students_education_history', sa.Column('title_uz', sa.String(), nullable=False))
    op.add_column('students_education_history', sa.Column('title_ru', sa.String(), nullable=False))
    op.add_column('students_education_history', sa.Column('title_uz_l', sa.String(), nullable=False))
    op.add_column('students_education_history', sa.Column('title_en', sa.String(), nullable=False))
    op.drop_column('students_education_history', 'place')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_education_history', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students_education_history', 'title_en')
    op.drop_column('students_education_history', 'title_uz_l')
    op.drop_column('students_education_history', 'title_ru')
    op.drop_column('students_education_history', 'title_uz')
    op.drop_column('students_education_history', 'order')
    # ### end Alembic commands ###
