"""empty message

Revision ID: 0b3290c45bcb
Revises: b55687666f03
Create Date: 2025-09-28 18:48:01.286975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3290c45bcb'
down_revision: Union[str, Sequence[str], None] = 'b55687666f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('semester_code', sa.String(length=512), nullable=False))
    op.drop_constraint(op.f('student_achievements_year_code_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'semesters', ['semester_code'], ['code'])
    op.drop_column('student_achievements', 'year_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('year_code', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_year_code_fkey'), 'student_achievements', 'education_years', ['year_code'], ['code'])
    op.drop_column('student_achievements', 'semester_code')
    # ### end Alembic commands ###
