"""empty message

Revision ID: 0f199394c517
Revises: 19590d19bae2
Create Date: 2025-10-14 23:11:21.799944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f199394c517'
down_revision: Union[str, Sequence[str], None] = '19590d19bae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_contact', 'owner',
               existing_type=postgresql.ENUM('father', 'mother', 'own', name='ownerenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_contact', 'owner',
               existing_type=sa.String(),
               type_=postgresql.ENUM('father', 'mother', 'own', name='ownerenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
