"""empty message

Revision ID: 14ba3f3b414c
Revises: 76c627c75b8d
Create Date: 2025-09-28 23:27:14.785923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ba3f3b414c'
down_revision: Union[str, Sequence[str], None] = '76c627c75b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student_achievements', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_achievements', 'statuses', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'status')
    op.drop_table('statuses')
    # ### end Alembic commands ###
