"""empty message

Revision ID: 174406544e39
Revises: 385be0e23b98
Create Date: 2025-10-14 00:36:25.121658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174406544e39'
down_revision: Union[str, Sequence[str], None] = '385be0e23b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_education_history', 'started_year',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('students_education_history', 'ended_year',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_education_history', 'ended_year',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('students_education_history', 'started_year',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
