"""empty message

Revision ID: 18264cf5256e
Revises: 3161cd01bf2a
Create Date: 2025-10-13 23:49:06.619290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18264cf5256e'
down_revision: Union[str, Sequence[str], None] = '3161cd01bf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_contact',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.Enum('father', 'mother', 'own', name='ownerenum'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_contact')
    # ### end Alembic commands ###
