"""empty message

Revision ID: 18577b2de9ec
Revises: 7a7dd71cf046
Create Date: 2025-10-12 23:04:32.820422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18577b2de9ec'
down_revision: Union[str, Sequence[str], None] = '7a7dd71cf046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychology_achievements', sa.Column('max_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychology_achievements', 'max_score')
    # ### end Alembic commands ###
