"""empty message

Revision ID: 19590d19bae2
Revises: 786a688a4ab1
Create Date: 2025-10-14 23:02:42.023647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19590d19bae2'
down_revision: Union[str, Sequence[str], None] = '786a688a4ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_contact_student_id_number_key'), 'students_contact', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('students_contact_student_id_number_key'), 'students_contact', ['student_id_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
