"""empty message

Revision ID: 3161cd01bf2a
Revises: 07a5596ba730
Create Date: 2025-10-13 16:08:38.718480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3161cd01bf2a'
down_revision: Union[str, Sequence[str], None] = '07a5596ba730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('student_achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'student_achievements', ['student_achievement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'student_achievement_id')
    # ### end Alembic commands ###
