"""empty message

Revision ID: 385be0e23b98
Revises: 8e11fbd9bc3e
Create Date: 2025-10-14 00:31:00.487983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385be0e23b98'
down_revision: Union[str, Sequence[str], None] = '8e11fbd9bc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_education_history', 'ended_year',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students_education_history', 'ended_year',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
