"""empty message

Revision ID: 3ac7f4fda020
Revises: 5662f5b892b7
Create Date: 2025-09-29 17:28:06.548805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac7f4fda020'
down_revision: Union[str, Sequence[str], None] = '5662f5b892b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpa',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('level_code', sa.String(length=512), nullable=False),
    sa.Column('education_type_code', sa.String(length=512), nullable=True),
    sa.Column('education_year_code', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['education_type_code'], ['education_types.code'], ),
    sa.ForeignKeyConstraint(['education_year_code'], ['education_years.code'], ),
    sa.ForeignKeyConstraint(['level_code'], ['levels.code'], ),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpa')
    # ### end Alembic commands ###
