"""empty message

Revision ID: 3c725b46196a
Revises: 6234865ce7e5
Create Date: 2025-10-12 21:45:30.904479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c725b46196a'
down_revision: Union[str, Sequence[str], None] = '6234865ce7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('education_year_code', sa.String(), nullable=False),
    sa.Column('semester_code', sa.String(), nullable=False),
    sa.Column('total_absences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id_number', 'education_year_code', 'semester_code', name='uq_attendance_student_year_semester')
    )
    op.create_index(op.f('ix_attendance_student_id_number'), 'attendance', ['student_id_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_student_id_number'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
