"""empty message

Revision ID: 47892e35661f
Revises: e9bff48d0e39
Create Date: 2025-10-07 01:57:47.495625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47892e35661f'
down_revision: Union[str, Sequence[str], None] = 'e9bff48d0e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('semesters_academic_year_code_fkey'), 'semesters', type_='foreignkey')
    op.drop_column('semesters', 'academic_year_code')
    op.drop_constraint(op.f('student_achievements_education_semester_code_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'semesters', ['education_semester_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_education_semester_code_fkey'), 'student_achievements', 'education_semesters', ['education_semester_code'], ['code'])
    op.add_column('semesters', sa.Column('academic_year_code', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('semesters_academic_year_code_fkey'), 'semesters', 'education_years', ['academic_year_code'], ['code'])
    # ### end Alembic commands ###
