"""empty message

Revision ID: 52016e1cf4ed
Revises: 6a616a7abe44
Create Date: 2025-10-07 00:40:46.810388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52016e1cf4ed'
down_revision: Union[str, Sequence[str], None] = '6a616a7abe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('is_upload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_types', 'is_upload')
    # ### end Alembic commands ###
