"""empty message

Revision ID: 5662f5b892b7
Revises: 6fe4ae41d133
Create Date: 2025-09-29 17:08:53.959011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5662f5b892b7'
down_revision: Union[str, Sequence[str], None] = '6fe4ae41d133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('education_semester_code', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'student_achievements', 'education_semesters', ['education_semester_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'education_semester_code')
    # ### end Alembic commands ###
