"""empty message

Revision ID: 5ad74dc361ff
Revises: 6df1984f6502
Create Date: 2025-10-07 16:14:51.712293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad74dc361ff'
down_revision: Union[str, Sequence[str], None] = '6df1984f6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('student_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_achievements', 'student_comment')
    # ### end Alembic commands ###
