"""empty message

Revision ID: 5b8cad7cb8b1
Revises: 7f694bae162d
Create Date: 2025-10-13 11:50:51.868982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8cad7cb8b1'
down_revision: Union[str, Sequence[str], None] = '7f694bae162d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychology_scorings', sa.Column('education_type_code', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'psychology_scorings', 'education_types', ['education_type_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psychology_scorings', type_='foreignkey')
    op.drop_column('psychology_scorings', 'education_type_code')
    # ### end Alembic commands ###
