"""empty message

Revision ID: 6a616a7abe44
Revises: 04422a8ee688
Create Date: 2025-10-06 22:46:20.724271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a616a7abe44'
down_revision: Union[str, Sequence[str], None] = '04422a8ee688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_types', 'can_upload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_types', sa.Column('can_upload', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
