"""empty message

Revision ID: 6d0991d758e6
Revises: 69b5f1c27e25
Create Date: 2025-10-18 01:04:08.858122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0991d758e6'
down_revision: Union[str, Sequence[str], None] = '69b5f1c27e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'short_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'second_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'third_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'third_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'second_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'short_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
