"""empty message

Revision ID: 6df1984f6502
Revises: 217709481222
Create Date: 2025-10-07 16:00:26.137587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df1984f6502'
down_revision: Union[str, Sequence[str], None] = '217709481222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('education_semester', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_achievements_education_semester_code_fkey'), 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'education_semester_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('education_semester_code', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_achievements_education_semester_code_fkey'), 'student_achievements', 'semesters', ['education_semester_code'], ['code'])
    op.drop_column('student_achievements', 'education_semester')
    # ### end Alembic commands ###
