"""empty message

Revision ID: 6fe4ae41d133
Revises: 14ba3f3b414c
Create Date: 2025-09-29 15:37:46.929549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe4ae41d133'
down_revision: Union[str, Sequence[str], None] = '14ba3f3b414c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_semesters',
    sa.Column('education_year_id', sa.String(length=512), nullable=False),
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['education_year_id'], ['education_years.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_semesters')
    # ### end Alembic commands ###
