"""empty message

Revision ID: 76c627c75b8d
Revises: 9e34ba434c44
Create Date: 2025-09-28 20:11:44.681005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c627c75b8d'
down_revision: Union[str, Sequence[str], None] = '9e34ba434c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_achievements_semester_code_fkey'), 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'semester_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('semester_code', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('student_achievements_semester_code_fkey'), 'student_achievements', 'semesters', ['semester_code'], ['code'])
    # ### end Alembic commands ###
