"""empty message

Revision ID: 7a7dd71cf046
Revises: 7ebc2385a63a
Create Date: 2025-10-12 22:27:55.712668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7dd71cf046'
down_revision: Union[str, Sequence[str], None] = '7ebc2385a63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychology_achievements',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychology_scorings',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('psychology_achievement_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('education_year_code', sa.String(), nullable=False),
    sa.Column('semester_code', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['psychology_achievement_id'], ['psychology_achievements.id'], ),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id_number', 'education_year_code', 'semester_code', name='uq_psychology_scoring_student_year_semester')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psychology_scorings')
    op.drop_table('psychology_achievements')
    # ### end Alembic commands ###
