"""empty message

Revision ID: 7ebc2385a63a
Revises: 3c725b46196a
Create Date: 2025-10-12 21:58:19.360939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebc2385a63a'
down_revision: Union[str, Sequence[str], None] = '3c725b46196a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_achievements', 'education_semester',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_foreign_key(None, 'student_achievements', 'semesters', ['education_semester'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.alter_column('student_achievements', 'education_semester',
               existing_type=sa.String(length=512),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
