"""empty message

Revision ID: 7f694bae162d
Revises: 428fc27fb043
Create Date: 2025-10-13 11:35:36.250404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f694bae162d'
down_revision: Union[str, Sequence[str], None] = '428fc27fb043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('education_type_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'education_type_code')
    # ### end Alembic commands ###
