"""empty message

Revision ID: 81db19af9302
Revises: 5ad74dc361ff
Create Date: 2025-10-07 16:28:44.997814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81db19af9302'
down_revision: Union[str, Sequence[str], None] = '5ad74dc361ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_achievements_status_fkey'), 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'statuses', ['status_id'], ['id'])
    op.drop_column('student_achievements', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('student_achievements_status_fkey'), 'student_achievements', 'statuses', ['status'], ['id'])
    op.drop_column('student_achievements', 'status_id')
    # ### end Alembic commands ###
