"""empty message

Revision ID: 8636389584b5
Revises: 174406544e39
Create Date: 2025-10-14 13:36:20.027304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8636389584b5'
down_revision: Union[str, Sequence[str], None] = '174406544e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_achievements', 'education_semester',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint(op.f('student_achievements_education_semester_fkey'), 'student_achievements', type_='foreignkey')
    op.drop_constraint(op.f('student_subjects_semester_code_fkey'), 'student_subjects', type_='foreignkey')
    op.drop_constraint(op.f('students_semester_code_fkey'), 'students', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('students_semester_code_fkey'), 'students', 'semesters', ['semester_code'], ['code'])
    op.create_foreign_key(op.f('student_subjects_semester_code_fkey'), 'student_subjects', 'semesters', ['semester_code'], ['code'])
    op.create_foreign_key(op.f('student_achievements_education_semester_fkey'), 'student_achievements', 'semesters', ['education_semester'], ['code'])
    op.alter_column('student_achievements', 'education_semester',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
