"""empty message

Revision ID: 8e11fbd9bc3e
Revises: f68c873d08d9
Create Date: 2025-10-14 00:16:37.238569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e11fbd9bc3e'
down_revision: Union[str, Sequence[str], None] = 'f68c873d08d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_education_history',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('started_year', sa.Date(), nullable=False),
    sa.Column('ended_year', sa.Date(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_education_history')
    # ### end Alembic commands ###
