"""empty message

Revision ID: 92dbe812c58f
Revises: 81db19af9302
Create Date: 2025-10-09 11:51:39.267244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dbe812c58f'
down_revision: Union[str, Sequence[str], None] = '81db19af9302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_years', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education_years', 'is_available')
    # ### end Alembic commands ###
