"""empty message

Revision ID: 9e34ba434c44
Revises: 76fbd26c89f4
Create Date: 2025-09-28 20:06:43.116992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e34ba434c44'
down_revision: Union[str, Sequence[str], None] = '76fbd26c89f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('education_year_code', sa.String(length=512), nullable=False))
    op.create_foreign_key(None, 'student_achievements', 'education_years', ['education_year_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'education_year_code')
    # ### end Alembic commands ###
