"""empty message

Revision ID: ad55e8bc52c2
Revises: 92dbe812c58f
Create Date: 2025-10-12 16:37:22.954483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad55e8bc52c2'
down_revision: Union[str, Sequence[str], None] = '92dbe812c58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_semesters', sa.Column('position_number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('education_semesters_education_year_id_fkey'), 'education_semesters', type_='foreignkey')
    op.drop_column('education_semesters', 'education_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_semesters', sa.Column('education_year_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('education_semesters_education_year_id_fkey'), 'education_semesters', 'education_years', ['education_year_id'], ['code'])
    op.drop_column('education_semesters', 'position_number')
    # ### end Alembic commands ###
