"""empty message

Revision ID: b55687666f03
Revises: 
Create Date: 2025-09-28 18:34:04.307226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55687666f03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_degrees',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('academic_ranks',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('accommodations',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('citizenships',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('education_forms',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('education_languages',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('education_types',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_types_code'), 'education_types', ['code'], unique=True)
    op.create_table('education_years',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employee_statuses',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employee_types',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employment_forms',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employment_staffs',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('genders',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('levels',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('locality_types',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('locations',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('province', 'district', 'terrain', name='locationtype'), nullable=False),
    sa.Column('parent_id', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_locations_type'), 'locations', ['type'], unique=False)
    op.create_table('payment_forms',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_categories',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('specialties',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('staff_positions',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('structure_types',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('student_statuses',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('student_types',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('universities',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('achievement_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=512), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['type'], ['education_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('structure_type_code', sa.String(length=512), nullable=False),
    sa.Column('locality_type_code', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['locality_type_code'], ['locality_types.code'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.external_id'], ),
    sa.ForeignKeyConstraint(['structure_type_code'], ['structure_types.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('education_lang_code', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['education_lang_code'], ['education_languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semesters',
    sa.Column('code', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('education_year', sa.String(length=512), nullable=True),
    sa.Column('academic_year_code', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['academic_year_code'], ['education_years.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('achievement_criteria',
    sa.Column('achievement_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['achievement_type_id'], ['achievement_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('login', sa.String(length=512), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=512), nullable=False),
    sa.Column('second_name', sa.String(length=512), nullable=False),
    sa.Column('third_name', sa.String(length=512), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_code', sa.String(length=512), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('year_of_enter', sa.Integer(), nullable=True),
    sa.Column('gender_code', sa.String(length=512), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.ForeignKeyConstraint(['gender_code'], ['genders.code'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id_number', sa.String(length=512), nullable=False),
    sa.Column('academic_degree_code', sa.String(length=512), nullable=False),
    sa.Column('academic_rank_code', sa.String(length=512), nullable=False),
    sa.Column('employment_form_code', sa.String(length=512), nullable=False),
    sa.Column('employment_staff_code', sa.String(length=512), nullable=False),
    sa.Column('staff_position_code', sa.String(length=512), nullable=False),
    sa.Column('employee_status_code', sa.String(length=512), nullable=False),
    sa.Column('employee_type_code', sa.String(length=512), nullable=False),
    sa.Column('contract_number', sa.String(length=512), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('decree_number', sa.String(length=512), nullable=False),
    sa.Column('decree_date', sa.Date(), nullable=True),
    sa.Column('specialty', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['academic_degree_code'], ['academic_degrees.code'], ),
    sa.ForeignKeyConstraint(['academic_rank_code'], ['academic_ranks.code'], ),
    sa.ForeignKeyConstraint(['employee_status_code'], ['employee_statuses.code'], ),
    sa.ForeignKeyConstraint(['employee_type_code'], ['employee_types.code'], ),
    sa.ForeignKeyConstraint(['employment_form_code'], ['employment_forms.code'], ),
    sa.ForeignKeyConstraint(['employment_staff_code'], ['employment_staffs.code'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_position_code'], ['staff_positions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_id_number'), 'employees', ['employee_id_number'], unique=True)
    op.create_table('psychologists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=512), nullable=False),
    sa.Column('license_number', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_code', sa.String(length=512), nullable=False),
    sa.Column('specialty_code', sa.String(length=512), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('semester_code', sa.String(length=512), nullable=False),
    sa.Column('education_year_code', sa.String(length=512), nullable=False),
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('avg_gpa', sa.Float(), nullable=False),
    sa.Column('avg_grade', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=512), nullable=False),
    sa.Column('province_code', sa.String(length=512), nullable=False),
    sa.Column('current_province_code', sa.String(length=512), nullable=True),
    sa.Column('district_code', sa.String(length=512), nullable=False),
    sa.Column('current_district_code', sa.String(length=512), nullable=True),
    sa.Column('terrain_code', sa.String(length=512), nullable=True),
    sa.Column('current_terrain_code', sa.String(length=512), nullable=True),
    sa.Column('citizenship_code', sa.String(length=512), nullable=False),
    sa.Column('student_status_code', sa.String(length=512), nullable=False),
    sa.Column('education_form_code', sa.String(length=512), nullable=False),
    sa.Column('education_type_code', sa.String(length=512), nullable=False),
    sa.Column('payment_form_code', sa.String(length=512), nullable=False),
    sa.Column('student_type_code', sa.String(length=512), nullable=False),
    sa.Column('social_category_code', sa.String(length=512), nullable=False),
    sa.Column('accommodation_code', sa.String(length=512), nullable=False),
    sa.Column('level_code', sa.String(length=512), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.Column('total_acload', sa.Integer(), nullable=True),
    sa.Column('is_graduate', sa.Boolean(), nullable=False),
    sa.Column('other', sa.String(length=512), nullable=True),
    sa.Column('validate_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_code'], ['accommodations.code'], ),
    sa.ForeignKeyConstraint(['citizenship_code'], ['citizenships.code'], ),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['current_district_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['current_province_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['current_terrain_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['district_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['education_form_code'], ['education_forms.code'], ),
    sa.ForeignKeyConstraint(['education_type_code'], ['education_types.code'], ),
    sa.ForeignKeyConstraint(['education_year_code'], ['education_years.code'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['level_code'], ['levels.code'], ),
    sa.ForeignKeyConstraint(['payment_form_code'], ['payment_forms.code'], ),
    sa.ForeignKeyConstraint(['province_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['semester_code'], ['semesters.code'], ),
    sa.ForeignKeyConstraint(['social_category_code'], ['social_categories.code'], ),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialties.code'], ),
    sa.ForeignKeyConstraint(['student_status_code'], ['student_statuses.code'], ),
    sa.ForeignKeyConstraint(['student_type_code'], ['student_types.code'], ),
    sa.ForeignKeyConstraint(['terrain_code'], ['locations.code'], ),
    sa.ForeignKeyConstraint(['university_code'], ['universities.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_student_id_number'), 'students', ['student_id_number'], unique=True)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('employee_history',
    sa.Column('employee_id', sa.String(length=512), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('third_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('year_of_enter', sa.Integer(), nullable=True),
    sa.Column('department_code', sa.String(), nullable=False),
    sa.Column('gender_code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('employee_id_number', sa.String(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('decree_number', sa.String(), nullable=False),
    sa.Column('decree_date', sa.Date(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('academic_degree_code', sa.String(), nullable=False),
    sa.Column('academic_rank_code', sa.String(), nullable=False),
    sa.Column('employment_form_code', sa.String(), nullable=False),
    sa.Column('employment_staff_code', sa.String(), nullable=False),
    sa.Column('staff_position_code', sa.String(), nullable=False),
    sa.Column('employee_status_code', sa.String(), nullable=False),
    sa.Column('employee_type_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id_number'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_history_external_id'), 'employee_history', ['external_id'], unique=False)
    op.create_table('student_achievements',
    sa.Column('student_id_number', sa.String(length=512), nullable=False),
    sa.Column('achievement_criteria_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('level_code', sa.String(length=512), nullable=False),
    sa.Column('year_code', sa.String(length=512), nullable=False),
    sa.Column('education_type_code', sa.String(length=512), nullable=True),
    sa.Column('moderator_comment', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['achievement_criteria_id'], ['achievement_criteria.id'], ),
    sa.ForeignKeyConstraint(['education_type_code'], ['education_types.code'], ),
    sa.ForeignKeyConstraint(['level_code'], ['levels.code'], ),
    sa.ForeignKeyConstraint(['student_id_number'], ['students.student_id_number'], ),
    sa.ForeignKeyConstraint(['year_code'], ['education_years.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_history',
    sa.Column('student_id', sa.String(length=512), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('third_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('year_of_enter', sa.Integer(), nullable=True),
    sa.Column('department_code', sa.String(), nullable=False),
    sa.Column('gender_code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('specialty_code', sa.String(length=512), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('education_form_code', sa.String(length=512), nullable=False),
    sa.Column('education_type_code', sa.String(length=512), nullable=False),
    sa.Column('level_code', sa.String(length=512), nullable=False),
    sa.Column('semester_code', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.String(length=512), nullable=False),
    sa.Column('social_category_code', sa.String(length=512), nullable=True),
    sa.Column('accommodation_code', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_history_external_id'), 'student_history', ['external_id'], unique=False)
    op.create_table('student_subjects',
    sa.Column('student_id', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_type_code', sa.String(), nullable=False),
    sa.Column('subject_type_name', sa.String(), nullable=False),
    sa.Column('exam_finish_code', sa.String(), nullable=False),
    sa.Column('exam_finish_name', sa.String(), nullable=False),
    sa.Column('semester_code', sa.String(length=512), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('total_acload', sa.Integer(), nullable=True),
    sa.Column('total_point', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('finish_credit_status', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['semester_code'], ['semesters.code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subjects')
    op.drop_index(op.f('ix_student_history_external_id'), table_name='student_history')
    op.drop_table('student_history')
    op.drop_table('student_achievements')
    op.drop_index(op.f('ix_employee_history_external_id'), table_name='employee_history')
    op.drop_table('employee_history')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_students_student_id_number'), table_name='students')
    op.drop_table('students')
    op.drop_table('psychologists')
    op.drop_index(op.f('ix_employees_employee_id_number'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('achievement_criteria')
    op.drop_table('semesters')
    op.drop_table('groups')
    op.drop_table('departments')
    op.drop_table('achievement_types')
    op.drop_table('universities')
    op.drop_table('student_types')
    op.drop_table('student_statuses')
    op.drop_table('structure_types')
    op.drop_table('staff_positions')
    op.drop_table('specialties')
    op.drop_table('social_categories')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('payment_forms')
    op.drop_index(op.f('ix_locations_type'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('locality_types')
    op.drop_table('levels')
    op.drop_table('genders')
    op.drop_table('employment_staffs')
    op.drop_table('employment_forms')
    op.drop_table('employee_types')
    op.drop_table('employee_statuses')
    op.drop_table('education_years')
    op.drop_index(op.f('ix_education_types_code'), table_name='education_types')
    op.drop_table('education_types')
    op.drop_table('education_languages')
    op.drop_table('education_forms')
    op.drop_table('countries')
    op.drop_table('citizenships')
    op.drop_table('accommodations')
    op.drop_table('academic_ranks')
    op.drop_table('academic_degrees')
    # ### end Alembic commands ###
