"""empty message

Revision ID: e9bff48d0e39
Revises: 52016e1cf4ed
Create Date: 2025-10-07 00:44:41.378287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bff48d0e39'
down_revision: Union[str, Sequence[str], None] = '52016e1cf4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education_types', 'code',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education_types', 'code',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
