"""empty message

Revision ID: f1296940655d
Revises: 08cacb95bcc3
Create Date: 2025-10-14 23:59:59.554065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1296940655d'
down_revision: Union[str, Sequence[str], None] = '08cacb95bcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['name'])
    op.drop_column('permissions', 'education_type_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('education_type_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
