"""empty message

Revision ID: f68c873d08d9
Revises: 18264cf5256e
Create Date: 2025-10-13 23:51:57.812741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68c873d08d9'
down_revision: Union[str, Sequence[str], None] = '18264cf5256e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students_contact', ['student_id_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_contact', type_='unique')
    # ### end Alembic commands ###
